server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duche27/office-ConfigServer
          clone-on-start: true
          # si no seteamos esto, busca rama 'main'
          default-label: kubernetes

eureka:
  instance:
    #    hostname: "${HOSTNAME}.eureka"
    hostname: eureka-0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka